### PR TITLE
sanketchaudhari10

### PR DESCRIPTION
**Pull request by sanketchaudhari10**
I have read the Code Of Conduct.

 I have followed all the steps of submission properly.

### CODE REVIEW

**Comment by yashpaneliya** [comment]
Hello, @sanketchaudhari10 ,
Your pull request has some merge conflict, kindly pull the latest version of the repository using `git pull` and update your pull request.

**Comment by sanketchaudhari10** [comment]
Sure thanks!!

**Comment by sanketchaudhari10** [comment]
@yashpaneliya  I have fixed the merge conflict. Please check if its mergeable. Thanks!!

**Review by yashpaneliya — APPROVED** [review]

**Comment by yashpaneliya** [comment]
Thanks, @sanketchaudhari10 , for opening the pull request! 👏

Star ⭐  this project and [tweet](https://twitter.com/share?text=Contributed+to+awesome+projects+at+@club_gamma&url=https://clubgamma.github.io/hacktoberfest) about your contributions and tag @clubgamma.

Also join the [Discord Server](https://discord.com/invite/kjnp6wU) for future updates

Ready to merge your PR!!!

**Pull request merged**
