### PR TITLE
meetxpress

### PR DESCRIPTION
**Pull request by meetxpress**
Here is the search bar with animation. As you click on the icon, it will provide you the space to add your text or search input. And if you want to close, just click on the cross. It will close with animation.

- [X] I have read the Code Of Conduct.
- [x] I have followed all the steps of submission properly.

### CODE REVIEW

**Review by rudrabarad — APPROVED** [review]

**Comment by rudrabarad** [comment]
> _No description provided._

Hello @meetxpress I've approved your PR. Now, you just need to include 2 lines in the description above regarding the code of conduct. Kindly go through our [CONTRIBUTING.md](https://github.com/clubgamma/Awesome-Web-Art/blob/master/CONTRIBUTING.md)

**Comment by meetxpress** [comment]
should I add more or this will be fine?

**Comment by meetxpress** [comment]
And can you help me with the conflict showing in the discussion?

**Comment by rudrabarad** [comment]
> should I add more or this will be fine?

Thankyou @meetxpress for a short description about your PR but the exact lines that you need to include are :
> - [X] I have read the Code Of Conduct.
> - [X] I have followed all the steps of submission properly.

**Comment by rudrabarad** [comment]
> And can you help me with the conflict showing in the discussion?

To solve those conflicts you can **Pull** the changes from the Club Gamma's Repository and update the **Pull Request**.
If you don't know how to do that don't worry I'll resolve those changes 😄

**Comment by meetxpress** [comment]
Oh, okay. Got you.

**Comment by meetxpress** [comment]
And will my PR get merged or not?

**Comment by meetxpress** [comment]
> > And can you help me with the conflict showing in the discussion?
> 
> To solve those conflicts you can **Pull** the changes from the Club Gamma's Repository and update the **Pull Request**.
> If you don't know how to do that don't worry I'll resolve those changes 😄

Can you teach me how to pull from Club Gamma's Repo?

**Comment by meetxpress** [comment]
It would be better if you do that for me. thank you for your help.

**Comment by rudrabarad** [comment]
> And will my PR get merged or not?

Definitely it will 💯

**Comment by rudrabarad** [comment]
Thanks, @meetxpress, for opening the pull request! 👏

Star ⭐  this project and [tweet](https://twitter.com/share?text=Contributed+to+awesome+projects+at+@club_gamma&url=https://clubgamma.github.io/hacktoberfest) about your contributions and tag @clubgamma.

Also join the [Discord Server](https://discord.com/invite/kjnp6wU)

We are ready to merge your PR!!!

**Pull request merged**
