### PR TITLE
thevrajshah

### PR DESCRIPTION
**Pull request by cheesetosht**
Created an animated Veggie Burger icon similar to the hamburger we commonly see in mobile apps. 

- [X]  I have read the Code Of Conduct.

- [X] I have followed all the steps of submission properly.

### CODE REVIEW

**Comment by yashpaneliya** [comment]
Hey @thevrajshah , your PR has some conflicts. Please pull the recent changes and edit your PR.

**Comment by cheesetosht** [comment]
Merge conflicts resloved

**Review by jayskhatri — CHANGES_REQUESTED** [review]
hey @thevrajshah you need to add your code in this repo

PR will be merged after you do changes 

Happy hacking✨

**Comment by rudrabarad** [comment]
Hello @thevrajshah it seems that while resolving the merge conflicts, you may have skipped to add the code in Pull Request. In this pull request in the **files changed tab** it shows that you have only made changes to the readme file.  So we request you to update this Pull request by adding a folder of your name in this pull request.

Thankyou

Happy hacking✨

**Comment by cheesetosht** [comment]
Sorry for the issue, I've made the relevant changes

**Review by jayskhatri — APPROVED** [review]
Good to go👍

**Pull request merged**
