### PR TITLE
imjp19

### PR DESCRIPTION
**Pull request by imjp19**
imjp19

### CODE REVIEW

**Comment by yashpaneliya** [comment]
Hey @imjp19 , Thanks for submitting PR.

Please change the comment according to [CONTRIBUTING.md](https://github.com/clubgamma/Awesome-Web-Art/blob/master/CONTRIBUTING.md). Then good to go.

Tweet about your contribution  and tag @clubgamma with #hacktoberfest2020.

Then wait for our team to review and merge your PR.

**Review by yashpaneliya — CHANGES_REQUESTED** [review]
Change the comment according to [CONTRIBUTING.md](https://github.com/clubgamma/Awesome-Web-Art/blob/master/CONTRIBUTING.md)

**Comment by imjp19** [comment]
- [X] I have read the Code Of Conduct.
        
  - [X] I have followed all the steps of submission properly.

**Review by yashpaneliya — APPROVED** [review]

**Review by yashpaneliya — APPROVED** [review]

**Comment by yashpaneliya** [comment]
Thanks, @imjp19, for opening the pull request! 👏

Star ⭐  this project and tweet about your contributions and tag @clubgamma.

**Pull request merged**
